# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Messenger' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Messenger

  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  
  pod 'Firebase/Crashlytics'

  # Add the Firebase pod for Google Analytics
  pod 'Firebase/Analytics'
  
  # Add for clould messaging. push notification
  pod 'Firebase/Messaging'
  
  
  pod 'FBSDKLoginKit'
  
  pod 'GoogleSignIn'
  
  pod 'MessageKit'
  pod 'JGProgressHUD'
#  pod 'RealmSwift'
  pod 'SDWebImage'

end
